name: Productivity Tracker - CI Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  # ==========================================
  # BACKEND CI
  # ==========================================
  backend-test:
    name: Backend Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install

      - name: Check Backend Syntax
        working-directory: backend
        run: node --check server.js


  # ==========================================
  # FRONTEND CI
  # ==========================================
  frontend-test:
    name: Frontend Build Test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install

      - name: Build Frontend
        working-directory: frontend
        run: npm run build


  # ==========================================
  # DOCKER BUILD TEST
  # ==========================================
  docker-build-test:
    name: Docker Build Test
    needs:
      - backend-test
      - frontend-test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build \
            -t productivity-tracker-backend:test \
            ./backend

      - name: Build Frontend Docker Image
        run: |
          docker build \
            -t productivity-tracker-frontend:test \
            ./frontend

      - name: Show Docker Images
        run: docker images
